* Invalid log files cause stack traces
  * biggest_hit = max(hit_list, key=hit_list.get)
    * ValueError: max() arg is an empty sequence
* debian: web2py starts up but acts weird when run as root
